version: '2'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
